# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]

  api-fastapi:
    build: ./services/api-fastapi
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISS: ${JWT_ISS}
      JWT_AUD: ${JWT_AUD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on: [postgres, redis]
    ports: ["${FASTAPI_PORT}:8000"]

  api-express:
    build: ./services/api-express
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISS: ${JWT_ISS}
      JWT_AUD: ${JWT_AUD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on: [postgres]
    ports: ["${EXPRESS_PORT}:4000"]

volumes:
  pgdata:
