# fly.toml app configuration file generated for cluesstack-api on 2025-11-02T17:55:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cluesstack-api'
primary_region = 'iad'

[build]
  dockerfile = 'services/api-fastapi/Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 30
    soft_limit = 20

  [[http_service.checks]]
    interval = '30s'
    timeout = '2s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
